python transformer_train.py \
  -exp_name local_glove \
  -src ../data/synthetic_1k/ \
  -model experiments/ \
  -corpus synthetic \
  -epochs 1000 \
  -batch_size 512 \
  -en glove \
  -de glove \
#  -resume_checkpoint experiments/local_elmo/synthetic.glove.glove.transformer.pt